package com.google.android.gms.internal.ads;

import android.content.Context;
import android.content.SharedPreferences.Editor;
import androidx.work.PeriodicWorkRequest;
import com.google.android.exoplayer2.DefaultRenderersFactory;
import com.google.android.exoplayer2.metadata.icy.IcyHeaders;
import com.google.android.exoplayer2.trackselection.AdaptiveTrackSelection;
import com.google.android.exoplayer2.upstream.DefaultLoadErrorHandlingPolicy;
import java.util.List;
import java.util.concurrent.TimeUnit;
import org.json.JSONObject;
import p043io.reactivex.annotations.SchedulerSupport;

@zzadh
public final class zznk {
    private static final zzna<String> zzaua = zzna.zza(0, "gads:sdk_core_experiment_id");
    public static final zzna<String> zzaub = zzna.zza(0, "gads:sdk_core_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40.html");
    private static final zzna<String> zzauc = zzna.zza(0, "gads:sdk_core_js_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.js");
    private static final zzna<Boolean> zzaud;
    private static final zzna<String> zzaue = zzna.zza(0, "gads:request_builder:singleton_webview_experiment_id");
    private static final zzna<Boolean> zzauf;
    private static final zzna<String> zzaug = zzna.zza(0, "gads:sdk_use_dynamic_module_experiment_id");
    public static final zzna<Boolean> zzauh;
    public static final zzna<Boolean> zzaui;
    public static final zzna<Boolean> zzauj;
    public static final zzna<String> zzauk = zzna.zza(0, "gads:sdk_crash_report_class_prefix", "com.google.");
    public static final zzna<Float> zzaul = zzna.zza(1, "gads:trapped_exception_sample_rate", 0.01f);
    public static final zzna<Boolean> zzaum;
    private static final zzna<String> zzaun = zzna.zza(0, "gads:block_autoclicks_experiment_id");
    private static final zzna<String> zzauo = zzna.zza(0, "gads:spam_app_context:experiment_id");
    private static final zzna<Integer> zzaup = zzna.zza(1, "gads:http_url_connection_factory:timeout_millis", 10000);
    public static final zzna<String> zzauq = zzna.zza(1, "gads:video_exo_player:version", IcyHeaders.REQUEST_HEADER_ENABLE_METADATA_VALUE);
    public static final zzna<Integer> zzaur = zzna.zza(1, "gads:video_exo_player:connect_timeout", 8000);
    public static final zzna<Integer> zzaus = zzna.zza(1, "gads:video_exo_player:read_timeout", 8000);
    public static final zzna<Integer> zzaut = zzna.zza(1, "gads:video_exo_player:loading_check_interval", 1048576);
    public static final zzna<Integer> zzauu = zzna.zza(1, "gads:video_exo_player:exo_player_precache_limit", Integer.MAX_VALUE);
    public static final zzna<Integer> zzauv = zzna.zza(1, "gads:video_exo_player:byte_buffer_precache_limit", Integer.MAX_VALUE);
    private static final zzna<String> zzauw = zzna.zza(0, "gads:video_stream_cache:experiment_id");
    public static final zzna<Integer> zzaux = zzna.zza(1, "gads:video_stream_cache:limit_count", 5);
    public static final zzna<Integer> zzauy = zzna.zza(1, "gads:video_stream_cache:limit_space", 8388608);
    public static final zzna<Integer> zzauz = zzna.zza(1, "gads:video_stream_exo_cache:buffer_size", 8388608);
    public static final zzna<Long> zzava = zzna.zza(1, "gads:video_stream_cache:limit_time_sec", 300);
    public static final zzna<Long> zzavb = zzna.zza(1, "gads:video_stream_cache:notify_interval_millis", 125);
    public static final zzna<Integer> zzavc = zzna.zza(1, "gads:video_stream_cache:connect_timeout_millis", 10000);
    public static final zzna<Boolean> zzavd;
    public static final zzna<String> zzave;
    public static final zzna<Long> zzavf = zzna.zza(1, "gads:video:metric_frame_hash_time_leniency", 500);
    public static final zzna<Boolean> zzavg;
    public static final zzna<Long> zzavh = zzna.zza(1, "gads:video:surface_update_min_spacing_ms", 1000);
    public static final zzna<Boolean> zzavi;
    public static final zzna<Integer> zzavj = zzna.zza(1, "gads:video:spinner:scale", 4);
    public static final zzna<Long> zzavk = zzna.zza(1, "gads:video:spinner:jank_threshold_ms", 50);
    public static final zzna<Boolean> zzavl;
    public static final zzna<Boolean> zzavm;
    public static final zzna<Boolean> zzavn;
    public static final zzna<String> zzavo;
    public static final zzna<Integer> zzavp = zzna.zza(1, "gads:video:codec_query_minimum_version", 16);
    private static final zzna<Boolean> zzavq;
    private static final zzna<Float> zzavr = zzna.zza(0, "gads:ad_id_app_context:ping_ratio", 0.0f);
    private static final zzna<String> zzavs = zzna.zza(0, "gads:ad_id_app_context:experiment_id");
    private static final zzna<String> zzavt = zzna.zza(0, "gads:ad_id_use_shared_preference:experiment_id");
    private static final zzna<Boolean> zzavu;
    private static final zzna<Float> zzavv = zzna.zza(0, "gads:ad_id_use_shared_preference:ping_ratio", 0.0f);
    private static final zzna<Boolean> zzavw;
    private static final zzna<Boolean> zzavx;
    private static final zzna<String> zzavy = zzna.zzb(0, "gads:looper_for_gms_client:experiment_id");
    public static final zzna<Boolean> zzavz;
    public static final zzna<Boolean> zzawa;
    private static final zzna<Boolean> zzawb;
    public static final zzna<String> zzawc = zzna.zza(1, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_banner.js");
    public static final zzna<String> zzawd = zzna.zza(1, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_expanded_banner.js");
    public static final zzna<String> zzawe = zzna.zza(1, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_interstitial.js");
    public static final zzna<String> zzawf = zzna.zza(1, "gad:mraid:version", "2.0");
    public static final zzna<Boolean> zzawg;
    public static final zzna<Boolean> zzawh;
    public static final zzna<String> zzawi = zzna.zza(0, "gads:sdk_csi_server", "https://csi.gstatic.com/csi");
    public static final zzna<Boolean> zzawj;
    public static final zzna<Boolean> zzawk;
    public static final zzna<Integer> zzawl = zzna.zza(0, "gads:content_length_weight", 1);
    public static final zzna<Integer> zzawm = zzna.zza(0, "gads:content_age_weight", 1);
    public static final zzna<Integer> zzawn = zzna.zza(0, "gads:min_content_len", 11);
    public static final zzna<Integer> zzawo = zzna.zza(0, "gads:fingerprint_number", 10);
    public static final zzna<Integer> zzawp = zzna.zza(0, "gads:sleep_sec", 10);
    public static final zzna<Boolean> zzawq;
    public static final zzna<Integer> zzawr = zzna.zza(1, "gads:content_vertical_fingerprint_number", 100);
    public static final zzna<Boolean> zzaws;
    public static final zzna<Integer> zzawt = zzna.zza(1, "gads:content_vertical_fingerprint_bits", 23);
    public static final zzna<Integer> zzawu = zzna.zza(1, "gads:content_vertical_fingerprint_ngram", 3);
    public static final zzna<String> zzawv = zzna.zza(1, "gads:content_fetch_view_tag_id", "googlebot");
    public static final zzna<String> zzaww = zzna.zza(1, "gads:content_fetch_exclude_view_tag", SchedulerSupport.NONE);
    public static final zzna<Boolean> zzawx;
    public static final zzna<Boolean> zzawy;
    public static final zzna<Boolean> zzawz;
    public static final zzna<Long> zzaxa = zzna.zza(0, "gads:app_index:timeout_ms", 1000);
    private static final zzna<String> zzaxb = zzna.zza(0, "gads:app_index:experiment_id");
    private static final zzna<String> zzaxc = zzna.zza(0, "gads:kitkat_interstitial_workaround:experiment_id");
    public static final zzna<Boolean> zzaxd;
    public static final zzna<Boolean> zzaxe;
    public static final zzna<Boolean> zzaxf;
    private static final zzna<String> zzaxg = zzna.zza(0, "gads:interstitial_follow_url:experiment_id");
    private static final zzna<Boolean> zzaxh;
    public static final zzna<Boolean> zzaxi;
    public static final zzna<Boolean> zzaxj;
    public static final zzna<Boolean> zzaxk;
    public static final zzna<Boolean> zzaxl;
    public static final zzna<Boolean> zzaxm;
    public static final zzna<Boolean> zzaxn;
    public static final zzna<String> zzaxo = zzna.zza(1, "gads:sai:click_ping_schema_v2", "^[^?]*(/aclk\\?|/pcs/click\\?).*");
    public static final zzna<String> zzaxp = zzna.zza(1, "gads:sai:impression_ping_schema_v2", "^[^?]*/adview.*");
    public static final zzna<Boolean> zzaxq;
    public static final zzna<Boolean> zzaxr;
    public static final zzna<String> zzaxs = zzna.zza(1, "gads:sai:ad_event_id_macro_name", "[gw_fbsaeid]");
    public static final zzna<Long> zzaxt = zzna.zza(1, "gads:sai:timeout_ms", -1);
    public static final zzna<Integer> zzaxu = zzna.zza(1, "gads:sai:scion_thread_pool_size", 5);
    public static final zzna<Boolean> zzaxv;
    private static final zzna<Integer> zzaxw = zzna.zza(0, "gads:webview_cache_version", 0);
    public static final zzna<Boolean> zzaxx;
    public static final zzna<Boolean> zzaxy;
    public static final zzna<Boolean> zzaxz;
    public static final zzna<Boolean> zzaya;
    public static final zzna<Boolean> zzayb;
    private static final zzna<String> zzayc = zzna.zzb(0, "gads:pan:experiment_id");
    public static final zzna<Boolean> zzayd;
    public static final zzna<Long> zzaye = zzna.zza(1, "gads:rewarded:adapter_timeout_ms", 20000);
    public static final zzna<Boolean> zzayf;
    public static final zzna<Boolean> zzayg;
    public static final zzna<Long> zzayh = zzna.zza(1, "gads:app_activity_tracker:notify_background_listeners_delay_ms", 500);
    public static final zzna<Long> zzayi = zzna.zza(1, "gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5));
    public static final zzna<Boolean> zzayj;
    public static final zzna<Long> zzayk = zzna.zza(1, "gads:adid_values_in_adrequest:timeout", (long) AdaptiveTrackSelection.DEFAULT_MIN_TIME_BETWEEN_BUFFER_REEVALUTATION_MS);
    public static final zzna<Boolean> zzayl;
    public static final zzna<Boolean> zzaym;
    private static final zzna<Boolean> zzayn;
    public static final zzna<Boolean> zzayo;
    public static final zzna<Boolean> zzayp;
    public static final zzna<Long> zzayq = zzna.zza(1, "gads:ad_overlay:delay_page_close_timeout_ms", (long) DefaultRenderersFactory.DEFAULT_ALLOWED_VIDEO_JOINING_TIME_MS);
    public static final zzna<Boolean> zzayr;
    public static final zzna<Boolean> zzays;
    public static final zzna<Boolean> zzayt;
    private static final zzna<Boolean> zzayu;
    private static final zzna<String> zzayv = zzna.zza(1, "gads:banner_ad_pool:schema", "customTargeting");
    private static final zzna<Integer> zzayw = zzna.zza(1, "gads:banner_ad_pool:max_queues", 3);
    private static final zzna<Integer> zzayx = zzna.zza(1, "gads:banner_ad_pool:max_pools", 3);
    public static final zzna<Boolean> zzayy;
    public static final zzna<Boolean> zzayz;
    public static final zzna<String> zzaza = zzna.zza(1, "gads:interstitial_ad_pool:schema", "customTargeting");
    public static final zzna<String> zzazb = zzna.zza(1, "gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
    public static final zzna<Integer> zzazc = zzna.zza(1, "gads:interstitial_ad_pool:max_pools", 3);
    public static final zzna<Integer> zzazd = zzna.zza(1, "gads:interstitial_ad_pool:max_pool_depth", 2);
    public static final zzna<Integer> zzaze = zzna.zza(1, "gads:interstitial_ad_pool:time_limit_sec", 1200);
    public static final zzna<String> zzazf;
    public static final zzna<Integer> zzazg = zzna.zza(1, "gads:interstitial_ad_pool:top_off_latency_min_millis", 0);
    public static final zzna<Integer> zzazh = zzna.zza(1, "gads:interstitial_ad_pool:top_off_latency_range_millis", 0);
    public static final zzna<Long> zzazi = zzna.zza(1, "gads:interstitial_ad_pool:discard_thresholds", 0);
    public static final zzna<Long> zzazj = zzna.zza(1, "gads:interstitial_ad_pool:miss_thresholds", 0);
    public static final zzna<Float> zzazk = zzna.zza(1, "gads:interstitial_ad_pool:discard_asymptote", 0.0f);
    public static final zzna<Float> zzazl = zzna.zza(1, "gads:interstitial_ad_pool:miss_asymptote", 0.0f);
    public static final zzna<Boolean> zzazm;
    public static final zzna<Boolean> zzazn;
    private static final zzna<Integer> zzazo = zzna.zza(1, "gads:heap_wastage:bytes", 0);
    public static final zzna<String> zzazp;
    public static final zzna<String> zzazq;
    public static final zzna<Boolean> zzazr;
    public static final zzna<Boolean> zzazs;
    public static final zzna<Long> zzazt = zzna.zza(1, "gads:position_watcher:throttle_ms", 200);
    public static final zzna<Boolean> zzazu;
    public static final zzna<Boolean> zzazv;
    public static final zzna<Long> zzazw = zzna.zza(0, "gads:device_info_caching_expiry_ms:expiry", (long) PeriodicWorkRequest.MIN_PERIODIC_FLEX_MILLIS);
    public static final zzna<Boolean> zzazx;
    public static final zzna<Boolean> zzazy;
    private static final zzna<Boolean> zzazz;
    private static final zzna<Boolean> zzbaa;
    private static final zzna<Boolean> zzbab;
    private static final zzna<Boolean> zzbac;
    public static final zzna<Boolean> zzbad;
    public static final zzna<Boolean> zzbae;
    private static final zzna<String> zzbaf = zzna.zza(0, "gads:gmsg:video_meta:experiment_id");
    private static final zzna<Long> zzbag = zzna.zza(1, "gads:network:cache_prediction_duration_s", 300);
    public static final zzna<Long> zzbah = zzna.zza(1, "gads:network:network_prediction_timeout_ms", (long) AdaptiveTrackSelection.DEFAULT_MIN_TIME_BETWEEN_BUFFER_REEVALUTATION_MS);
    public static final zzna<Boolean> zzbai;
    public static final zzna<Boolean> zzbaj;
    public static final zzna<Boolean> zzbak;
    private static final zzna<Long> zzbal = zzna.zza(1, "gads:rtb_signal_timeout_ms", 1000);
    public static final zzna<Long> zzbam = zzna.zza(0, "gads:resolve_future:default_timeout_ms", 30000);
    public static final zzna<Long> zzban = zzna.zza(0, "gads:ad_loader:timeout_ms", (long) DefaultLoadErrorHandlingPolicy.DEFAULT_TRACK_BLACKLIST_MS);
    public static final zzna<Long> zzbao = zzna.zza(0, "gads:rendering:timeout_ms", (long) DefaultLoadErrorHandlingPolicy.DEFAULT_TRACK_BLACKLIST_MS);
    public static final zzna<Boolean> zzbap;
    public static final zzna<Long> zzbaq = zzna.zza(1, "gads:gestures:task_timeout", (long) AdaptiveTrackSelection.DEFAULT_MIN_TIME_BETWEEN_BUFFER_REEVALUTATION_MS);
    public static final zzna<Boolean> zzbar;
    public static final zzna<Boolean> zzbas;
    public static final zzna<Boolean> zzbat;
    public static final zzna<Boolean> zzbau;
    public static final zzna<Boolean> zzbav;
    public static final zzna<Boolean> zzbaw;
    public static final zzna<String> zzbax;
    public static final zzna<Boolean> zzbay;
    public static final zzna<Boolean> zzbaz;
    public static final zzna<Boolean> zzbba;
    public static final zzna<Boolean> zzbbb;
    public static final zzna<Boolean> zzbbc;
    public static final zzna<Boolean> zzbbd;
    private static final zzna<Boolean> zzbbe;
    private static final zzna<Boolean> zzbbf;
    public static final zzna<Boolean> zzbbg;
    public static final zzna<Boolean> zzbbh;
    private static final zzna<String> zzbbi = zzna.zza(0, "gads:use_get_drawing_cache_for_screenshot:experiment_id");
    private static final zzna<String> zzbbj = zzna.zza(1, "gads:sdk_core_constants:experiment_id");
    public static final zzna<String> zzbbk;
    public static final zzna<Long> zzbbl = zzna.zza(0, "gads:js_flags:update_interval", TimeUnit.HOURS.toMillis(12));
    public static final zzna<Boolean> zzbbm;
    private static final zzna<Boolean> zzbbn;
    public static final zzna<Boolean> zzbbo;
    public static final zzna<String> zzbbp = zzna.zza(1, "gads:native:engine_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
    private static final zzna<String> zzbbq = zzna.zza(0, "gads:native:engine_js_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/native_ads.js");
    private static final zzna<String> zzbbr = zzna.zza(1, "gads:native:video_url", "//imasdk.googleapis.com/admob/sdkloader/native_video.html");
    public static final zzna<String> zzbbs = zzna.zza(1, "gads:native:video_url_with_protocol", "https://imasdk.googleapis.com/admob/sdkloader/native_video.html");
    private static final zzna<String> zzbbt = zzna.zza(1, "gads:singleton_webview_native:experiment_id");
    public static final zzna<Boolean> zzbbu;
    public static final zzna<Boolean> zzbbv;
    public static final zzna<Boolean> zzbbw;
    public static final zzna<Integer> zzbbx = zzna.zza(1, "gads:native_video_load_timeout", 10);
    public static final zzna<Integer> zzbby = zzna.zza(1, "gads:omid:native_webview_load_timeout", 2000);
    public static final zzna<String> zzbbz = zzna.zza(1, "gads:ad_choices_content_description", "Ad Choices Icon");
    public static final zzna<Boolean> zzbca;
    public static final zzna<Boolean> zzbcb;
    public static final zzna<Boolean> zzbcc;
    public static final zzna<Boolean> zzbcd;
    public static final zzna<Boolean> zzbce;
    public static final zzna<Boolean> zzbcf;
    public static final zzna<Boolean> zzbcg;
    public static final zzna<Boolean> zzbch;
    public static final zzna<Boolean> zzbci;
    public static final zzna<Long> zzbcj = zzna.zza(0, "gads:method_tracing:duration_ms", 30000);
    public static final zzna<Integer> zzbck = zzna.zza(0, "gads:method_tracing:count", 5);
    public static final zzna<Integer> zzbcl = zzna.zza(0, "gads:method_tracing:filesize", 134217728);
    private static final zzna<Boolean> zzbcm;
    private static final zzna<String> zzbcn = zzna.zzb(1, "gads:auto_location_for_coarse_permission:experiment_id");
    public static final zzna<Long> zzbco = zzna.zza(1, "gads:auto_location_timeout", (long) AdaptiveTrackSelection.DEFAULT_MIN_TIME_BETWEEN_BUFFER_REEVALUTATION_MS);
    private static final zzna<String> zzbcp = zzna.zzb(1, "gads:auto_location_timeout:experiment_id");
    private static final zzna<Long> zzbcq = zzna.zza(1, "gads:auto_location_interval", -1);
    private static final zzna<String> zzbcr = zzna.zzb(1, "gads:auto_location_interval:experiment_id");
    public static final zzna<Boolean> zzbcs;
    private static final zzna<String> zzbct = zzna.zza(1, "gads:fetch_app_settings_using_cld:enabled:experiment_id");
    public static final zzna<Long> zzbcu = zzna.zza(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000);
    private static final zzna<String> zzbcv = zzna.zza(0, "gads:afs:csa:experiment_id");
    public static final zzna<String> zzbcw = zzna.zza(0, "gads:afs:csa_webview_gmsg_ad_failed", "gmsg://noAdLoaded");
    public static final zzna<String> zzbcx = zzna.zza(0, "gads:afs:csa_webview_gmsg_script_load_failed", "gmsg://scriptLoadFailed");
    public static final zzna<String> zzbcy = zzna.zza(0, "gads:afs:csa_webview_gmsg_ad_loaded", "gmsg://adResized");
    public static final zzna<String> zzbcz = zzna.zza(0, "gads:afs:csa_webview_static_file_path", "/afs/ads/i/webview.html");
    public static final zzna<String> zzbda = zzna.zza(0, "gads:afs:csa_webview_custom_domain_param_key", "csa_customDomain");
    public static final zzna<Long> zzbdb = zzna.zza(0, "gads:afs:csa_webview_adshield_timeout_ms", 1000);
    private static final zzna<Boolean> zzbdc;
    private static final zzna<Boolean> zzbdd;
    private static final zzna<Boolean> zzbde;
    public static final zzna<Long> zzbdf = zzna.zza(1, "gads:parental_controls:timeout", (long) AdaptiveTrackSelection.DEFAULT_MIN_TIME_BETWEEN_BUFFER_REEVALUTATION_MS);
    private static final zzna<String> zzbdg = zzna.zza(0, "gads:safe_browsing:api_key", "AIzaSyDRKQ9d6kfsoZT2lUnZcZnBYvH69HExNPE");
    private static final zzna<Long> zzbdh = zzna.zza(0, "gads:safe_browsing:safety_net:delay_ms", (long) AdaptiveTrackSelection.DEFAULT_MIN_TIME_BETWEEN_BUFFER_REEVALUTATION_MS);
    public static final zzna<Boolean> zzbdi;
    public static final zzna<Boolean> zzbdj;
    private static final zzna<Integer> zzbdk = zzna.zza(1, "gads:cache:ad_request_timeout_millis", 250);
    private static final zzna<Integer> zzbdl = zzna.zza(1, "gads:cache:max_concurrent_downloads", 10);
    private static final zzna<Long> zzbdm = zzna.zza(1, "gads:cache:javascript_timeout_millis", (long) DefaultRenderersFactory.DEFAULT_ALLOWED_VIDEO_JOINING_TIME_MS);
    public static final zzna<Boolean> zzbdn;
    public static final zzna<Boolean> zzbdo;
    public static final zzna<Boolean> zzbdp;
    public static final zzna<Long> zzbdq = zzna.zza(1, "gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30));
    public static final zzna<Boolean> zzbdr;
    private static final zzna<Boolean> zzbds;
    private static final zzna<Long> zzbdt = zzna.zza(1, "gads:cache:connection_timeout", (long) DefaultRenderersFactory.DEFAULT_ALLOWED_VIDEO_JOINING_TIME_MS);
    private static final zzna<Long> zzbdu = zzna.zza(1, "gads:cache:read_only_connection_timeout", (long) DefaultRenderersFactory.DEFAULT_ALLOWED_VIDEO_JOINING_TIME_MS);
    public static final zzna<Boolean> zzbdv;
    public static final zzna<String> zzbdw = zzna.zza(1, "gads:http_assets_cache:regex", "(?i)https:\\/\\/(tpc\\.googlesyndication\\.com\\/(.*)|lh\\d+\\.googleusercontent\\.com\\/(.*))");
    public static final zzna<Integer> zzbdx = zzna.zza(1, "gads:http_assets_cache:time_out", 100);
    public static final zzna<Boolean> zzbdy;
    public static final zzna<Boolean> zzbdz;
    public static final zzna<Boolean> zzbea;
    public static final zzna<Boolean> zzbeb;
    public static final zzna<Boolean> zzbec;
    public static final zzna<Boolean> zzbed;
    public static final zzna<Long> zzbee = zzna.zza(1, "gads:debug_hold_gesture:time_millis", (long) AdaptiveTrackSelection.DEFAULT_MIN_TIME_BETWEEN_BUFFER_REEVALUTATION_MS);
    public static final zzna<String> zzbef = zzna.zza(1, "gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice");
    public static final zzna<String> zzbeg = zzna.zza(1, "gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview");
    public static final zzna<String> zzbeh = zzna.zza(1, "gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals");
    public static final zzna<String> zzbei = zzna.zza(1, "gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData");
    public static final zzna<Integer> zzbej = zzna.zza(1, "gads:drx_debug:timeout_ms", 5000);
    public static final zzna<Integer> zzbek = zzna.zza(1, "gad:pixel_dp_comparision_multiplier", 1);
    public static final zzna<Boolean> zzbel;
    public static final zzna<Boolean> zzbem;
    public static final zzna<Integer> zzben = zzna.zza(1, "gad:interstitial:close_button_padding_dip", 0);
    public static final zzna<Boolean> zzbeo;
    public static final zzna<Boolean> zzbep;
    public static final zzna<Boolean> zzbeq;
    public static final zzna<Boolean> zzber;
    public static final zzna<Integer> zzbes = zzna.zza(1, "gad:http_redirect_max_count:times", 8);
    public static final zzna<Boolean> zzbet;
    private static final zzna<Boolean> zzbeu;
    private static final zzna<Boolean> zzbev;
    private static final zzna<String> zzbew;
    private static final zzna<Boolean> zzbex;
    private static final zzna<String> zzbey;
    private static final zzna<Boolean> zzbez;
    private static final zzna<Boolean> zzbfa;
    private static final zzna<String> zzbfb;
    private static final zzna<Boolean> zzbfc;
    private static final zzna<String> zzbfd;
    public static final zzna<Boolean> zzbfe;
    private static final zzna<Boolean> zzbff;
    private static final zzna<Boolean> zzbfg;
    private static final zzna<Boolean> zzbfh;
    private static final zzna<Boolean> zzbfi;
    private static final zzna<Boolean> zzbfj;
    private static final zzna<Boolean> zzbfk;
    private static final zzna<Boolean> zzbfl;
    private static final zzna<Boolean> zzbfm;
    public static final zzna<Long> zzbfn = zzna.zza(1, "gads:mobius_linking:sdk_side_cooldown_time_threshold:ms", 3600000);
    public static final zzna<String> zzbfo = zzna.zza(0, "gads:public_beta:traffic_multiplier", "1.0");
    public static final zzna<Boolean> zzbfp;
    public static final zzna<Boolean> zzbfq;
    public static final zzna<Boolean> zzbfr;
    public static final zzna<Integer> zzbfs = zzna.zza(1, "gads:adoverlay:b68684796:targeting_sdk:lower_bound", 27);
    public static final zzna<Integer> zzbft = zzna.zza(1, "gads:adoverlay:b68684796:targeting_sdk:upper_bound", 27);
    public static final zzna<Integer> zzbfu = zzna.zza(1, "gads:adoverlay:b68684796:sdk_int:lower_bound", 26);
    public static final zzna<Integer> zzbfv = zzna.zza(1, "gads:adoverlay:b68684796:sdk_int:upper_bound", 27);
    private static byte[] zzbfw;

    static {
        Boolean valueOf = Boolean.valueOf(false);
        zzaud = zzna.zza(0, "gads:request_builder:singleton_webview", valueOf);
        Boolean valueOf2 = Boolean.valueOf(true);
        zzauf = zzna.zza(0, "gads:sdk_use_dynamic_module", valueOf2);
        zzauh = zzna.zza(0, "gads:sdk_crash_report_enabled", valueOf);
        zzaui = zzna.zza(0, "gads:report_dynamite_crash_in_background_thread", valueOf);
        zzauj = zzna.zza(0, "gads:sdk_crash_report_full_stacktrace", valueOf);
        zzaum = zzna.zza(0, "gads:block_autoclicks", valueOf);
        zzavd = zzna.zza(0, "gads:video:metric_reporting_enabled", valueOf);
        String str = "";
        zzave = zzna.zza(1, "gads:video:metric_frame_hash_times", str);
        zzavg = zzna.zza(1, "gads:video:force_watermark", valueOf);
        zzavi = zzna.zza(1, "gads:video:spinner:enabled", valueOf);
        zzavl = zzna.zza(1, "gads:video:aggressive_media_codec_release", valueOf);
        zzavm = zzna.zza(1, "gads:memory_bundle:debug_info", valueOf);
        zzavn = zzna.zza(1, "gads:memory_bundle:runtime_info", valueOf2);
        zzavo = zzna.zza(1, "gads:video:codec_query_mime_types", str);
        zzavq = zzna.zza(0, "gads:ad_id_app_context:enabled", valueOf);
        zzavu = zzna.zza(0, "gads:ad_id_use_shared_preference:enabled", valueOf);
        zzavw = zzna.zza(0, "gads:ad_id_use_persistent_service:enabled", valueOf);
        zzavx = zzna.zza(0, "gads:ad_id:use_ipc:enabled", valueOf);
        zzavz = zzna.zza(0, "gads:looper_for_gms_client:enabled", valueOf2);
        zzawa = zzna.zza(0, "gads:sw_ad_request_service:enabled", valueOf2);
        zzawb = zzna.zza(0, "gads:sw_dynamite:enabled", valueOf2);
        zzawg = zzna.zza(1, "gads:mraid:unload", valueOf);
        zzawh = zzna.zza(0, "gads:enabled_sdk_csi", valueOf);
        zzawj = zzna.zza(0, "gads:sdk_csi_write_to_file", valueOf);
        zzawk = zzna.zza(0, "gads:enable_content_fetching", valueOf2);
        zzawq = zzna.zza(1, "gads:enable_content_url_hash", valueOf2);
        zzaws = zzna.zza(1, "gads:enable_content_vertical_hash", valueOf2);
        zzawx = zzna.zza(0, "gad:app_index_enabled", valueOf2);
        zzawy = zzna.zza(1, "gads:content_fetch_disable_get_title_from_webview", valueOf);
        zzawz = zzna.zza(0, "gads:app_index:without_content_info_present:enabled", valueOf2);
        zzaxd = zzna.zza(0, "gads:kitkat_interstitial_workaround:enabled", valueOf2);
        zzaxe = zzna.zza(0, "gads:interstitial_follow_url", valueOf2);
        zzaxf = zzna.zza(0, "gads:interstitial_follow_url:register_click", valueOf2);
        zzaxh = zzna.zza(0, "gads:analytics_enabled", valueOf2);
        zzaxi = zzna.zza(0, "gads:ad_key_enabled", valueOf);
        zzaxj = zzna.zza(1, "gads:sai:enabled", valueOf2);
        zzaxk = zzna.zza(1, "gads:sai:banner_ad_enabled", valueOf2);
        zzaxl = zzna.zza(1, "gads:sai:native_ad_enabled", valueOf2);
        zzaxm = zzna.zza(1, "gads:sai:interstitial_ad_enabled", valueOf2);
        zzaxn = zzna.zza(1, "gads:sai:rewardedvideo_ad_enabled", valueOf2);
        zzaxq = zzna.zza(1, "gads:sai:click_gmsg_enabled", valueOf2);
        zzaxr = zzna.zza(1, "gads:sai:using_macro:enabled", valueOf);
        zzaxv = zzna.zza(1, "gads:x_seconds_rewarded:enable", valueOf);
        zzaxx = zzna.zza(1, "gads:webview:ignore_over_scroll", valueOf2);
        zzaxy = zzna.zza(0, "gads:corewebview:adwebview_factory:enable", valueOf);
        zzaxz = zzna.zza(0, "gads:corewebview:javascript_engine", valueOf);
        zzaya = zzna.zza(1, "gad:webview:inject_scripts", valueOf);
        zzayb = zzna.zza(0, "gads:webview:permission:disabled", valueOf);
        zzayd = zzna.zza(1, "gads:rewarded:adapter_initialization_enabled", valueOf);
        zzayf = zzna.zza(1, "gads:rewarded:ad_metadata_enabled", valueOf);
        zzayg = zzna.zza(1, "gads:app_activity_tracker:enabled", valueOf2);
        zzayj = zzna.zza(1, "gads:adid_values_in_adrequest:enabled", valueOf);
        zzayl = zzna.zza(1, "gads:disable_adid_values_in_ms", valueOf);
        zzaym = zzna.zza(1, "gads:enable_ad_loader_manager", valueOf2);
        zzayn = zzna.zza(0, "gads:ad_serving:enabled", valueOf2);
        zzayo = zzna.zza(1, "gads:ad_manager_enforce_arp_invariant:enabled", valueOf2);
        zzayp = zzna.zza(1, "gads:ad_manager:admob_extra:new_bundle", valueOf2);
        zzayr = zzna.zza(1, "gads:interstitial_ad_immersive_mode", valueOf2);
        zzays = zzna.zza(1, "gads:custom_close_blocking:enabled", valueOf);
        zzayt = zzna.zza(1, "gads:disabling_closable_area:enabled", valueOf);
        zzayu = zzna.zza(1, "gads:impression_optimization_enabled", valueOf);
        zzayy = zzna.zza(1, "gads:interstitial_ad_pool:enabled", valueOf);
        zzayz = zzna.zza(1, "gads:interstitial_ad_pool:enabled_for_rewarded", valueOf);
        String str2 = "(?!)";
        zzazf = zzna.zza(1, "gads:interstitial_ad_pool:ad_unit_exclusions", str2);
        zzazm = zzna.zza(0, "gads:debug_logging_feature:enable", valueOf);
        zzazn = zzna.zza(0, "gads:debug_logging_feature:intercept_web_view", valueOf);
        zzazp = zzna.zza(1, "gads:spherical_video:vertex_shader", str);
        zzazq = zzna.zza(1, "gads:spherical_video:fragment_shader", str);
        zzazr = zzna.zza(0, "gads:log:verbose_enabled", valueOf);
        zzazs = zzna.zza(1, "gads:include_local_global_rectangles", valueOf);
        zzazu = zzna.zza(1, "gads:include_lock_screen_apps_for_visibility", valueOf2);
        zzazv = zzna.zza(0, "gads:device_info_caching:enabled", valueOf2);
        zzazx = zzna.zza(1, "gads:gen204_signals:enabled", valueOf);
        zzazy = zzna.zza(0, "gads:webview:error_reporting_enabled", valueOf);
        zzazz = zzna.zza(0, "gads:adid_reporting:enabled", valueOf);
        zzbaa = zzna.zza(0, "gads:ad_settings_page_reporting:enabled", valueOf);
        zzbab = zzna.zza(0, "gads:adid_info_gmscore_upgrade_reporting:enabled", valueOf);
        zzbac = zzna.zza(0, "gads:request_pkg:enabled", valueOf2);
        zzbad = zzna.zza(1, "gads:gmsg:disable_back_button:enabled", valueOf2);
        zzbae = zzna.zza(0, "gads:gmsg:video_meta:enabled", valueOf2);
        zzbai = zzna.zza(0, "gads:mediation:dynamite_first:admobadapter", valueOf2);
        zzbaj = zzna.zza(0, "gads:mediation:dynamite_first:adurladapter", valueOf2);
        zzbak = zzna.zza(1, "gads:bypass_adrequest_service_for_inlined_mediation", valueOf2);
        zzbap = zzna.zza(0, "gads:adshield:enable_adshield_instrumentation", valueOf);
        zzbar = zzna.zza(1, "gads:gestures:asig:enabled", valueOf);
        zzbas = zzna.zza(1, "gads:gestures:ans:enabled", valueOf);
        zzbat = zzna.zza(1, "gads:gestures:tos:enabled", valueOf);
        zzbau = zzna.zza(1, "gads:signal:app_permissions:disabled", valueOf);
        zzbav = zzna.zza(1, "gads:gestures:inthex:enabled", valueOf);
        zzbaw = zzna.zza(1, "gads:gestures:hpk:enabled", valueOf2);
        zzbax = zzna.zza(1, "gads:gestures:pk", str);
        zzbay = zzna.zza(1, "gads:gestures:bs:enabled", valueOf2);
        zzbaz = zzna.zza(1, "gads:gestures:check_initialization_thread:enabled", valueOf);
        zzbba = zzna.zza(1, "gads:gestures:get_query_in_non_ui_thread:enabled", valueOf2);
        zzbbb = zzna.zza(0, "gass:enabled", valueOf2);
        zzbbc = zzna.zza(0, "gass:enable_int_signal", valueOf2);
        zzbbd = zzna.zza(0, "gass:enable_ad_attestation_signal", valueOf2);
        zzbbe = zzna.zza(0, "gads:adid_notification:first_party_check:enabled", valueOf2);
        zzbbf = zzna.zza(0, "gads:edu_device_helper:enabled", valueOf2);
        zzbbg = zzna.zza(0, "gads:support_screen_shot", valueOf2);
        zzbbh = zzna.zza(0, "gads:use_get_drawing_cache_for_screenshot:enabled", valueOf2);
        zzbbk = zzna.zza(1, "gads:sdk_core_constants:caps", str);
        zzbbm = zzna.zza(0, "gads:js_flags:mf", valueOf);
        zzbbn = zzna.zza(1, "gads:js_flags:disable_phenotype", valueOf);
        zzbbo = zzna.zza(0, "gads:custom_render:ping_on_ad_rendered", valueOf);
        zzbbu = zzna.zza(1, "gads:enable_untrack_view_native", valueOf2);
        zzbbv = zzna.zza(1, "gads:ignore_untrack_view_google_native", valueOf2);
        zzbbw = zzna.zza(1, "gads:reset_listeners_preparead_native", valueOf2);
        zzbca = zzna.zza(1, "gads:clamp_native_video_player_dimensions", valueOf2);
        zzbcb = zzna.zza(1, "gads:enable_store_active_view_state", valueOf);
        zzbcc = zzna.zza(1, "gads:enable_singleton_broadcast_receiver", valueOf);
        zzbcd = zzna.zza(1, "gads:native:overlay_new_fix:enabled", valueOf2);
        zzbce = zzna.zza(1, "gads:native:count_impression_for_assets", valueOf);
        zzbcf = zzna.zza(1, "gads:native:custom_one_point_five_click:enable", valueOf2);
        zzbcg = zzna.zza(1, "gads:unified_native_ad:enable", valueOf2);
        zzbch = zzna.zza(1, "gads:fluid_ad:use_wrap_content_height", valueOf);
        zzbci = zzna.zza(0, "gads:method_tracing:enabled", valueOf);
        zzbcm = zzna.zza(1, "gads:auto_location_for_coarse_permission", valueOf);
        zzbcs = zzna.zza(1, "gads:fetch_app_settings_using_cld:enabled", valueOf);
        zzbdc = zzna.zza(0, "gads:afs:csa_ad_manager_enabled", valueOf2);
        zzbdd = zzna.zza(1, "gads:parental_controls:send_from_client", valueOf2);
        zzbde = zzna.zza(1, "gads:parental_controls:cache_results", valueOf2);
        zzbdi = zzna.zza(0, "gads:safe_browsing:debug", valueOf);
        zzbdj = zzna.zza(0, "gads:webview_cookie:enabled", valueOf2);
        zzbdn = zzna.zza(1, "gads:cache:bind_on_foreground", valueOf);
        zzbdo = zzna.zza(1, "gads:cache:bind_on_init", valueOf);
        zzbdp = zzna.zza(1, "gads:cache:bind_on_request", valueOf);
        zzbdr = zzna.zza(1, "gads:cache:use_cache_data_source", valueOf);
        zzbds = zzna.zza(1, "gads:cache:connection_per_read", valueOf);
        zzbdv = zzna.zza(1, "gads:http_assets_cache:enabled", valueOf);
        zzbdy = zzna.zza(1, "gads:chrome_custom_tabs:enabled", valueOf2);
        zzbdz = zzna.zza(1, "gads:chrome_custom_tabs_browser:enabled", valueOf);
        zzbea = zzna.zza(1, "gads:chrome_custom_tabs:disabled", valueOf);
        zzbeb = zzna.zza(1, "gads:drx_in_app_preview:enabled", valueOf2);
        zzbec = zzna.zza(1, "gads:drx_debug_signals:enabled", valueOf2);
        zzbed = zzna.zza(1, "gads:debug_hold_gesture:enabled", valueOf);
        zzbel = zzna.zza(1, "gad:interstitial_for_multi_window", valueOf);
        zzbem = zzna.zza(1, "gad:interstitial_ad_stay_active_in_multi_window", valueOf);
        zzbeo = zzna.zza(1, "gads:clearcut_logging:enabled", valueOf);
        zzbep = zzna.zza(1, "gads:clearcut_logging:write_to_file", valueOf);
        zzbeq = zzna.zza(0, "gad:force_local_ad_request_service:enabled", valueOf);
        zzber = zzna.zza(0, "gad:force_dynamite_loading_enabled", valueOf);
        zzbet = zzna.zza(1, "gads:omid:enabled", valueOf);
        zzbeu = zzna.zza(0, "gads:nonagon:red_button", valueOf);
        zzbev = zzna.zza(1, "gads:nonagon:banner:enabled", valueOf);
        zzbew = zzna.zza(1, "gads:nonagon:banner:ad_unit_exclusions", str2);
        zzbex = zzna.zza(1, "gads:nonagon:interstitial:enabled", valueOf);
        zzbey = zzna.zza(1, "gads:nonagon:interstitial:ad_unit_exclusions", str2);
        zzbez = zzna.zza(1, "gads:nonagon:rewardedvideo:enabled", valueOf);
        zzbfa = zzna.zza(1, "gads:nonagon:mobile_ads_setting_manager:enabled", valueOf);
        zzbfb = zzna.zza(1, "gads:nonagon:rewardedvideo:ad_unit_exclusions", str2);
        zzbfc = zzna.zza(1, "gads:nonagon:nativead:enabled", valueOf);
        zzbfd = zzna.zza(1, "gads:nonagon:nativead:app_name", str2);
        zzbfe = zzna.zza(1, "gads:nonagon:banner:check_dp_size", valueOf);
        zzbff = zzna.zza(1, "gads:nonagon:service:enabled", valueOf);
        zzbfg = zzna.zza(1, "gads:signals:ad_id_info:enabled", valueOf);
        zzbfh = zzna.zza(1, "gads:signals:app_index:enabled", valueOf);
        zzbfi = zzna.zza(1, "gads:signals:cache:enabled", valueOf);
        zzbfj = zzna.zza(1, "gads:signals:doritos:enabled", valueOf);
        zzbfk = zzna.zza(1, "gads:signals:location:enabled", valueOf);
        zzbfl = zzna.zza(1, "gads:signals:network_prediction:enabled", valueOf);
        zzbfm = zzna.zza(1, "gads:signals:parental_control:enabled", valueOf);
        zzbfp = zzna.zza(1, "gads:real_test_request:enabled", valueOf2);
        zzbfq = zzna.zza(1, "gads:real_test_request:render_webview_label", valueOf2);
        zzbfr = zzna.zza(1, "gads:real_test_request:render_native_label", valueOf2);
    }

    public static void initialize(Context context) {
        zzaml.zza(context, new zznl(context));
        int intValue = ((Integer) zzkb.zzik().zzd(zzazo)).intValue();
        if (intValue > 0 && zzbfw == null) {
            zzbfw = new byte[intValue];
        }
    }

    public static void zza(Context context, int i, JSONObject jSONObject) {
        zzkb.zzii();
        Editor edit = context.getSharedPreferences("google_ads_flags", 0).edit();
        zzkb.zzij().zza(edit, 1, jSONObject);
        zzkb.zzii();
        edit.commit();
    }

    public static List<String> zzjb() {
        return zzkb.zzij().zzjb();
    }

    public static List<String> zzjc() {
        return zzkb.zzij().zzjc();
    }
}
