package p043io.opencensus.contrib.grpc.metrics;

import com.google.firebase.remoteconfig.FirebaseRemoteConfig;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import p043io.opencensus.common.Duration;
import p043io.opencensus.stats.Aggregation;
import p043io.opencensus.stats.Aggregation.Count;
import p043io.opencensus.stats.Aggregation.Distribution;
import p043io.opencensus.stats.Aggregation.Mean;
import p043io.opencensus.stats.BucketBoundaries;
import p043io.opencensus.stats.View;
import p043io.opencensus.stats.View.AggregationWindow;
import p043io.opencensus.stats.View.AggregationWindow.Cumulative;
import p043io.opencensus.stats.View.AggregationWindow.Interval;
import p043io.opencensus.stats.View.Name;
import p043io.opencensus.tags.TagKey;

/* renamed from: io.opencensus.contrib.grpc.metrics.RpcViewConstants */
public final class RpcViewConstants {
    static final Aggregation AGGREGATION_WITH_BYTES_HISTOGRAM = Distribution.create(BucketBoundaries.create(RPC_BYTES_BUCKET_BOUNDARIES));
    static final Aggregation AGGREGATION_WITH_COUNT_HISTOGRAM = Distribution.create(BucketBoundaries.create(RPC_COUNT_BUCKET_BOUNDARIES));
    static final Aggregation AGGREGATION_WITH_MILLIS_HISTOGRAM = Distribution.create(BucketBoundaries.create(RPC_MILLIS_BUCKET_BOUNDARIES));
    static final Aggregation COUNT = Count.create();
    static final AggregationWindow CUMULATIVE = Cumulative.create();
    static final Duration HOUR = Duration.create(3600, 0);
    static final AggregationWindow INTERVAL_HOUR = Interval.create(HOUR);
    static final AggregationWindow INTERVAL_MINUTE = Interval.create(MINUTE);
    static final Aggregation MEAN = Mean.create();
    static final Duration MINUTE = Duration.create(60, 0);
    static final List<Double> RPC_BYTES_BUCKET_BOUNDARIES;
    public static final View RPC_CLIENT_ERROR_COUNT_HOUR_VIEW;
    public static final View RPC_CLIENT_ERROR_COUNT_MINUTE_VIEW;
    public static final View RPC_CLIENT_ERROR_COUNT_VIEW;
    public static final View RPC_CLIENT_FINISHED_COUNT_CUMULATIVE_VIEW;
    public static final View RPC_CLIENT_FINISHED_COUNT_HOUR_VIEW;
    public static final View RPC_CLIENT_FINISHED_COUNT_MINUTE_VIEW;
    public static final View RPC_CLIENT_REQUEST_BYTES_HOUR_VIEW;
    public static final View RPC_CLIENT_REQUEST_BYTES_MINUTE_VIEW;
    public static final View RPC_CLIENT_REQUEST_BYTES_VIEW;
    public static final View RPC_CLIENT_REQUEST_COUNT_HOUR_VIEW;
    public static final View RPC_CLIENT_REQUEST_COUNT_MINUTE_VIEW;
    public static final View RPC_CLIENT_REQUEST_COUNT_VIEW;
    public static final View RPC_CLIENT_RESPONSE_BYTES_HOUR_VIEW;
    public static final View RPC_CLIENT_RESPONSE_BYTES_MINUTE_VIEW;
    public static final View RPC_CLIENT_RESPONSE_BYTES_VIEW;
    public static final View RPC_CLIENT_RESPONSE_COUNT_HOUR_VIEW;
    public static final View RPC_CLIENT_RESPONSE_COUNT_MINUTE_VIEW;
    public static final View RPC_CLIENT_RESPONSE_COUNT_VIEW;
    public static final View RPC_CLIENT_ROUNDTRIP_LATENCY_HOUR_VIEW;
    public static final View RPC_CLIENT_ROUNDTRIP_LATENCY_MINUTE_VIEW;
    public static final View RPC_CLIENT_ROUNDTRIP_LATENCY_VIEW;
    public static final View RPC_CLIENT_SERVER_ELAPSED_TIME_HOUR_VIEW;
    public static final View RPC_CLIENT_SERVER_ELAPSED_TIME_MINUTE_VIEW;
    public static final View RPC_CLIENT_SERVER_ELAPSED_TIME_VIEW;
    public static final View RPC_CLIENT_STARTED_COUNT_CUMULATIVE_VIEW;
    public static final View RPC_CLIENT_STARTED_COUNT_HOUR_VIEW;
    public static final View RPC_CLIENT_STARTED_COUNT_MINUTE_VIEW;
    public static final View RPC_CLIENT_UNCOMPRESSED_REQUEST_BYTES_HOUR_VIEW;
    public static final View RPC_CLIENT_UNCOMPRESSED_REQUEST_BYTES_MINUTE_VIEW;
    public static final View RPC_CLIENT_UNCOMPRESSED_REQUEST_BYTES_VIEW;
    public static final View RPC_CLIENT_UNCOMPRESSED_RESPONSE_BYTES_HOUR_VIEW;
    public static final View RPC_CLIENT_UNCOMPRESSED_RESPONSE_BYTES_MINUTE_VIEW;
    public static final View RPC_CLIENT_UNCOMPRESSED_RESPONSE_BYTES_VIEW;
    static final List<Double> RPC_COUNT_BUCKET_BOUNDARIES;
    static final List<Double> RPC_MILLIS_BUCKET_BOUNDARIES;
    public static final View RPC_SERVER_ERROR_COUNT_HOUR_VIEW;
    public static final View RPC_SERVER_ERROR_COUNT_MINUTE_VIEW;
    public static final View RPC_SERVER_ERROR_COUNT_VIEW;
    public static final View RPC_SERVER_FINISHED_COUNT_CUMULATIVE_VIEW;
    public static final View RPC_SERVER_FINISHED_COUNT_HOUR_VIEW;
    public static final View RPC_SERVER_FINISHED_COUNT_MINUTE_VIEW;
    public static final View RPC_SERVER_REQUEST_BYTES_HOUR_VIEW;
    public static final View RPC_SERVER_REQUEST_BYTES_MINUTE_VIEW;
    public static final View RPC_SERVER_REQUEST_BYTES_VIEW;
    public static final View RPC_SERVER_REQUEST_COUNT_HOUR_VIEW;
    public static final View RPC_SERVER_REQUEST_COUNT_MINUTE_VIEW;
    public static final View RPC_SERVER_REQUEST_COUNT_VIEW;
    public static final View RPC_SERVER_RESPONSE_BYTES_HOUR_VIEW;
    public static final View RPC_SERVER_RESPONSE_BYTES_MINUTE_VIEW;
    public static final View RPC_SERVER_RESPONSE_BYTES_VIEW;
    public static final View RPC_SERVER_RESPONSE_COUNT_HOUR_VIEW;
    public static final View RPC_SERVER_RESPONSE_COUNT_MINUTE_VIEW;
    public static final View RPC_SERVER_RESPONSE_COUNT_VIEW;
    public static final View RPC_SERVER_SERVER_ELAPSED_TIME_HOUR_VIEW;
    public static final View RPC_SERVER_SERVER_ELAPSED_TIME_MINUTE_VIEW;
    public static final View RPC_SERVER_SERVER_ELAPSED_TIME_VIEW;
    public static final View RPC_SERVER_SERVER_LATENCY_HOUR_VIEW;
    public static final View RPC_SERVER_SERVER_LATENCY_MINUTE_VIEW;
    public static final View RPC_SERVER_SERVER_LATENCY_VIEW;
    public static final View RPC_SERVER_STARTED_COUNT_CUMULATIVE_VIEW;
    public static final View RPC_SERVER_STARTED_COUNT_HOUR_VIEW;
    public static final View RPC_SERVER_STARTED_COUNT_MINUTE_VIEW;
    public static final View RPC_SERVER_UNCOMPRESSED_REQUEST_BYTES_HOUR_VIEW;
    public static final View RPC_SERVER_UNCOMPRESSED_REQUEST_BYTES_MINUTE_VIEW;
    public static final View RPC_SERVER_UNCOMPRESSED_REQUEST_BYTES_VIEW;
    public static final View RPC_SERVER_UNCOMPRESSED_RESPONSE_BYTES_HOUR_VIEW;
    public static final View RPC_SERVER_UNCOMPRESSED_RESPONSE_BYTES_MINUTE_VIEW;
    public static final View RPC_SERVER_UNCOMPRESSED_RESPONSE_BYTES_VIEW;

    static {
        Double valueOf = Double.valueOf(FirebaseRemoteConfig.DEFAULT_VALUE_FOR_DOUBLE);
        RPC_BYTES_BUCKET_BOUNDARIES = Collections.unmodifiableList(Arrays.asList(new Double[]{valueOf, Double.valueOf(1024.0d), Double.valueOf(2048.0d), Double.valueOf(4096.0d), Double.valueOf(16384.0d), Double.valueOf(65536.0d), Double.valueOf(262144.0d), Double.valueOf(1048576.0d), Double.valueOf(4194304.0d), Double.valueOf(1.6777216E7d), Double.valueOf(6.7108864E7d), Double.valueOf(2.68435456E8d), Double.valueOf(1.073741824E9d), Double.valueOf(4.294967296E9d)}));
        RPC_MILLIS_BUCKET_BOUNDARIES = Collections.unmodifiableList(Arrays.asList(new Double[]{valueOf, Double.valueOf(1.0d), Double.valueOf(2.0d), Double.valueOf(3.0d), Double.valueOf(4.0d), Double.valueOf(5.0d), Double.valueOf(6.0d), Double.valueOf(8.0d), Double.valueOf(10.0d), Double.valueOf(13.0d), Double.valueOf(16.0d), Double.valueOf(20.0d), Double.valueOf(25.0d), Double.valueOf(30.0d), Double.valueOf(40.0d), Double.valueOf(50.0d), Double.valueOf(65.0d), Double.valueOf(80.0d), Double.valueOf(100.0d), Double.valueOf(130.0d), Double.valueOf(160.0d), Double.valueOf(200.0d), Double.valueOf(250.0d), Double.valueOf(300.0d), Double.valueOf(400.0d), Double.valueOf(500.0d), Double.valueOf(650.0d), Double.valueOf(800.0d), Double.valueOf(1000.0d), Double.valueOf(2000.0d), Double.valueOf(5000.0d), Double.valueOf(10000.0d), Double.valueOf(20000.0d), Double.valueOf(50000.0d), Double.valueOf(100000.0d)}));
        RPC_COUNT_BUCKET_BOUNDARIES = Collections.unmodifiableList(Arrays.asList(new Double[]{valueOf, Double.valueOf(1.0d), Double.valueOf(2.0d), Double.valueOf(4.0d), Double.valueOf(8.0d), Double.valueOf(16.0d), Double.valueOf(32.0d), Double.valueOf(64.0d), Double.valueOf(128.0d), Double.valueOf(256.0d), Double.valueOf(512.0d), Double.valueOf(1024.0d), Double.valueOf(2048.0d), Double.valueOf(4096.0d), Double.valueOf(8192.0d), Double.valueOf(16384.0d), Double.valueOf(32768.0d), Double.valueOf(65536.0d)}));
        String str = "RPC Errors";
        RPC_CLIENT_ERROR_COUNT_VIEW = View.create(Name.create("grpc.io/client/error_count/cumulative"), str, RpcMeasureConstants.RPC_CLIENT_ERROR_COUNT, MEAN, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_STATUS, RpcMeasureConstants.RPC_METHOD}), CUMULATIVE);
        String str2 = "Latency in msecs";
        RPC_CLIENT_ROUNDTRIP_LATENCY_VIEW = View.create(Name.create("grpc.io/client/roundtrip_latency/cumulative"), str2, RpcMeasureConstants.RPC_CLIENT_ROUNDTRIP_LATENCY, AGGREGATION_WITH_MILLIS_HISTOGRAM, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), CUMULATIVE);
        String str3 = "Server elapsed time in msecs";
        RPC_CLIENT_SERVER_ELAPSED_TIME_VIEW = View.create(Name.create("grpc.io/client/server_elapsed_time/cumulative"), str3, RpcMeasureConstants.RPC_CLIENT_SERVER_ELAPSED_TIME, AGGREGATION_WITH_MILLIS_HISTOGRAM, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), CUMULATIVE);
        String str4 = "Request bytes";
        RPC_CLIENT_REQUEST_BYTES_VIEW = View.create(Name.create("grpc.io/client/request_bytes/cumulative"), str4, RpcMeasureConstants.RPC_CLIENT_REQUEST_BYTES, AGGREGATION_WITH_BYTES_HISTOGRAM, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), CUMULATIVE);
        String str5 = "Response bytes";
        RPC_CLIENT_RESPONSE_BYTES_VIEW = View.create(Name.create("grpc.io/client/response_bytes/cumulative"), str5, RpcMeasureConstants.RPC_CLIENT_RESPONSE_BYTES, AGGREGATION_WITH_BYTES_HISTOGRAM, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), CUMULATIVE);
        String str6 = "Uncompressed Request bytes";
        RPC_CLIENT_UNCOMPRESSED_REQUEST_BYTES_VIEW = View.create(Name.create("grpc.io/client/uncompressed_request_bytes/cumulative"), str6, RpcMeasureConstants.RPC_CLIENT_UNCOMPRESSED_REQUEST_BYTES, AGGREGATION_WITH_BYTES_HISTOGRAM, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), CUMULATIVE);
        String str7 = "Uncompressed Response bytes";
        RPC_CLIENT_UNCOMPRESSED_RESPONSE_BYTES_VIEW = View.create(Name.create("grpc.io/client/uncompressed_response_bytes/cumulative"), str7, RpcMeasureConstants.RPC_CLIENT_UNCOMPRESSED_RESPONSE_BYTES, AGGREGATION_WITH_BYTES_HISTOGRAM, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), CUMULATIVE);
        String str8 = "Count of request messages per client RPC";
        RPC_CLIENT_REQUEST_COUNT_VIEW = View.create(Name.create("grpc.io/client/request_count/cumulative"), str8, RpcMeasureConstants.RPC_CLIENT_REQUEST_COUNT, AGGREGATION_WITH_COUNT_HISTOGRAM, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), CUMULATIVE);
        String str9 = "Count of response messages per client RPC";
        RPC_CLIENT_RESPONSE_COUNT_VIEW = View.create(Name.create("grpc.io/client/response_count/cumulative"), str9, RpcMeasureConstants.RPC_CLIENT_RESPONSE_COUNT, AGGREGATION_WITH_COUNT_HISTOGRAM, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), CUMULATIVE);
        String str10 = "Number of started client RPCs";
        RPC_CLIENT_STARTED_COUNT_CUMULATIVE_VIEW = View.create(Name.create("grpc.io/client/started_count/cumulative"), str10, RpcMeasureConstants.RPC_CLIENT_STARTED_COUNT, COUNT, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), CUMULATIVE);
        String str11 = "Number of finished client RPCs";
        RPC_CLIENT_FINISHED_COUNT_CUMULATIVE_VIEW = View.create(Name.create("grpc.io/client/finished_count/cumulative"), str11, RpcMeasureConstants.RPC_CLIENT_FINISHED_COUNT, COUNT, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), CUMULATIVE);
        String str12 = "RPC Errors";
        RPC_SERVER_ERROR_COUNT_VIEW = View.create(Name.create("grpc.io/server/error_count/cumulative"), str12, RpcMeasureConstants.RPC_SERVER_ERROR_COUNT, MEAN, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_STATUS, RpcMeasureConstants.RPC_METHOD}), CUMULATIVE);
        String str13 = "Latency in msecs";
        RPC_SERVER_SERVER_LATENCY_VIEW = View.create(Name.create("grpc.io/server/server_latency/cumulative"), str13, RpcMeasureConstants.RPC_SERVER_SERVER_LATENCY, AGGREGATION_WITH_MILLIS_HISTOGRAM, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), CUMULATIVE);
        String str14 = "Server elapsed time in msecs";
        RPC_SERVER_SERVER_ELAPSED_TIME_VIEW = View.create(Name.create("grpc.io/server/elapsed_time/cumulative"), str14, RpcMeasureConstants.RPC_SERVER_SERVER_ELAPSED_TIME, AGGREGATION_WITH_MILLIS_HISTOGRAM, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), CUMULATIVE);
        String str15 = "Request bytes";
        RPC_SERVER_REQUEST_BYTES_VIEW = View.create(Name.create("grpc.io/server/request_bytes/cumulative"), str15, RpcMeasureConstants.RPC_SERVER_REQUEST_BYTES, AGGREGATION_WITH_BYTES_HISTOGRAM, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), CUMULATIVE);
        String str16 = "Response bytes";
        RPC_SERVER_RESPONSE_BYTES_VIEW = View.create(Name.create("grpc.io/server/response_bytes/cumulative"), str16, RpcMeasureConstants.RPC_SERVER_RESPONSE_BYTES, AGGREGATION_WITH_BYTES_HISTOGRAM, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), CUMULATIVE);
        String str17 = "Uncompressed Request bytes";
        RPC_SERVER_UNCOMPRESSED_REQUEST_BYTES_VIEW = View.create(Name.create("grpc.io/server/uncompressed_request_bytes/cumulative"), str17, RpcMeasureConstants.RPC_SERVER_UNCOMPRESSED_REQUEST_BYTES, AGGREGATION_WITH_BYTES_HISTOGRAM, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), CUMULATIVE);
        String str18 = "Uncompressed Response bytes";
        RPC_SERVER_UNCOMPRESSED_RESPONSE_BYTES_VIEW = View.create(Name.create("grpc.io/server/uncompressed_response_bytes/cumulative"), str18, RpcMeasureConstants.RPC_SERVER_UNCOMPRESSED_RESPONSE_BYTES, AGGREGATION_WITH_BYTES_HISTOGRAM, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), CUMULATIVE);
        String str19 = "Count of request messages per server RPC";
        RPC_SERVER_REQUEST_COUNT_VIEW = View.create(Name.create("grpc.io/server/request_count/cumulative"), str19, RpcMeasureConstants.RPC_SERVER_REQUEST_COUNT, AGGREGATION_WITH_COUNT_HISTOGRAM, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), CUMULATIVE);
        String str20 = "Count of response messages per server RPC";
        RPC_SERVER_RESPONSE_COUNT_VIEW = View.create(Name.create("grpc.io/server/response_count/cumulative"), str20, RpcMeasureConstants.RPC_SERVER_RESPONSE_COUNT, AGGREGATION_WITH_COUNT_HISTOGRAM, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), CUMULATIVE);
        String str21 = "Number of started server RPCs";
        RPC_SERVER_STARTED_COUNT_CUMULATIVE_VIEW = View.create(Name.create("grpc.io/server/started_count/cumulative"), str21, RpcMeasureConstants.RPC_SERVER_STARTED_COUNT, COUNT, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), CUMULATIVE);
        String str22 = "Number of finished server RPCs";
        RPC_SERVER_FINISHED_COUNT_CUMULATIVE_VIEW = View.create(Name.create("grpc.io/server/finished_count/cumulative"), str22, RpcMeasureConstants.RPC_SERVER_FINISHED_COUNT, COUNT, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), CUMULATIVE);
        String str23 = "Minute stats for latency in msecs";
        RPC_CLIENT_ROUNDTRIP_LATENCY_MINUTE_VIEW = View.create(Name.create("grpc.io/client/roundtrip_latency/minute"), str23, RpcMeasureConstants.RPC_CLIENT_ROUNDTRIP_LATENCY, MEAN, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_MINUTE);
        String str24 = "Minute stats for request size in bytes";
        RPC_CLIENT_REQUEST_BYTES_MINUTE_VIEW = View.create(Name.create("grpc.io/client/request_bytes/minute"), str24, RpcMeasureConstants.RPC_CLIENT_REQUEST_BYTES, MEAN, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_MINUTE);
        String str25 = "Minute stats for response size in bytes";
        RPC_CLIENT_RESPONSE_BYTES_MINUTE_VIEW = View.create(Name.create("grpc.io/client/response_bytes/minute"), str25, RpcMeasureConstants.RPC_CLIENT_RESPONSE_BYTES, MEAN, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_MINUTE);
        String str26 = "Minute stats for rpc errors";
        RPC_CLIENT_ERROR_COUNT_MINUTE_VIEW = View.create(Name.create("grpc.io/client/error_count/minute"), str26, RpcMeasureConstants.RPC_CLIENT_ERROR_COUNT, MEAN, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_MINUTE);
        String str27 = "Minute stats for uncompressed request size in bytes";
        RPC_CLIENT_UNCOMPRESSED_REQUEST_BYTES_MINUTE_VIEW = View.create(Name.create("grpc.io/client/uncompressed_request_bytes/minute"), str27, RpcMeasureConstants.RPC_CLIENT_UNCOMPRESSED_REQUEST_BYTES, MEAN, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_MINUTE);
        String str28 = "Minute stats for uncompressed response size in bytes";
        RPC_CLIENT_UNCOMPRESSED_RESPONSE_BYTES_MINUTE_VIEW = View.create(Name.create("grpc.io/client/uncompressed_response_bytes/minute"), str28, RpcMeasureConstants.RPC_CLIENT_UNCOMPRESSED_RESPONSE_BYTES, MEAN, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_MINUTE);
        String str29 = "Minute stats for server elapsed time in msecs";
        RPC_CLIENT_SERVER_ELAPSED_TIME_MINUTE_VIEW = View.create(Name.create("grpc.io/client/server_elapsed_time/minute"), str29, RpcMeasureConstants.RPC_CLIENT_SERVER_ELAPSED_TIME, MEAN, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_MINUTE);
        String str30 = "Minute stats on the number of client RPCs started";
        RPC_CLIENT_STARTED_COUNT_MINUTE_VIEW = View.create(Name.create("grpc.io/client/started_count/minute"), str30, RpcMeasureConstants.RPC_CLIENT_STARTED_COUNT, COUNT, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_MINUTE);
        String str31 = "Minute stats on the number of client RPCs finished";
        RPC_CLIENT_FINISHED_COUNT_MINUTE_VIEW = View.create(Name.create("grpc.io/client/finished_count/minute"), str31, RpcMeasureConstants.RPC_CLIENT_FINISHED_COUNT, COUNT, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_MINUTE);
        String str32 = "Minute stats on the count of request messages per client RPC";
        RPC_CLIENT_REQUEST_COUNT_MINUTE_VIEW = View.create(Name.create("grpc.io/client/request_count/minute"), str32, RpcMeasureConstants.RPC_CLIENT_REQUEST_COUNT, MEAN, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_MINUTE);
        String str33 = "Minute stats on the count of response messages per client RPC";
        RPC_CLIENT_RESPONSE_COUNT_MINUTE_VIEW = View.create(Name.create("grpc.io/client/response_count/minute"), str33, RpcMeasureConstants.RPC_CLIENT_RESPONSE_COUNT, MEAN, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_MINUTE);
        String str34 = "Hour stats for latency in msecs";
        RPC_CLIENT_ROUNDTRIP_LATENCY_HOUR_VIEW = View.create(Name.create("grpc.io/client/roundtrip_latency/hour"), str34, RpcMeasureConstants.RPC_CLIENT_ROUNDTRIP_LATENCY, MEAN, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_HOUR);
        String str35 = "Hour stats for request size in bytes";
        RPC_CLIENT_REQUEST_BYTES_HOUR_VIEW = View.create(Name.create("grpc.io/client/request_bytes/hour"), str35, RpcMeasureConstants.RPC_CLIENT_REQUEST_BYTES, MEAN, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_HOUR);
        String str36 = "Hour stats for response size in bytes";
        RPC_CLIENT_RESPONSE_BYTES_HOUR_VIEW = View.create(Name.create("grpc.io/client/response_bytes/hour"), str36, RpcMeasureConstants.RPC_CLIENT_RESPONSE_BYTES, MEAN, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_HOUR);
        String str37 = "Hour stats for rpc errors";
        RPC_CLIENT_ERROR_COUNT_HOUR_VIEW = View.create(Name.create("grpc.io/client/error_count/hour"), str37, RpcMeasureConstants.RPC_CLIENT_ERROR_COUNT, MEAN, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_HOUR);
        String str38 = "Hour stats for uncompressed request size in bytes";
        RPC_CLIENT_UNCOMPRESSED_REQUEST_BYTES_HOUR_VIEW = View.create(Name.create("grpc.io/client/uncompressed_request_bytes/hour"), str38, RpcMeasureConstants.RPC_CLIENT_UNCOMPRESSED_REQUEST_BYTES, MEAN, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_HOUR);
        String str39 = "Hour stats for uncompressed response size in bytes";
        RPC_CLIENT_UNCOMPRESSED_RESPONSE_BYTES_HOUR_VIEW = View.create(Name.create("grpc.io/client/uncompressed_response_bytes/hour"), str39, RpcMeasureConstants.RPC_CLIENT_UNCOMPRESSED_RESPONSE_BYTES, MEAN, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_HOUR);
        String str40 = "Hour stats for server elapsed time in msecs";
        RPC_CLIENT_SERVER_ELAPSED_TIME_HOUR_VIEW = View.create(Name.create("grpc.io/client/server_elapsed_time/hour"), str40, RpcMeasureConstants.RPC_CLIENT_SERVER_ELAPSED_TIME, MEAN, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_HOUR);
        String str41 = "Hour stats on the number of client RPCs started";
        RPC_CLIENT_STARTED_COUNT_HOUR_VIEW = View.create(Name.create("grpc.io/client/started_count/hour"), str41, RpcMeasureConstants.RPC_CLIENT_STARTED_COUNT, COUNT, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_HOUR);
        String str42 = "Hour stats on the number of client RPCs finished";
        RPC_CLIENT_FINISHED_COUNT_HOUR_VIEW = View.create(Name.create("grpc.io/client/finished_count/hour"), str42, RpcMeasureConstants.RPC_CLIENT_FINISHED_COUNT, COUNT, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_HOUR);
        String str43 = "Hour stats on the count of request messages per client RPC";
        RPC_CLIENT_REQUEST_COUNT_HOUR_VIEW = View.create(Name.create("grpc.io/client/request_count/hour"), str43, RpcMeasureConstants.RPC_CLIENT_REQUEST_COUNT, MEAN, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_HOUR);
        String str44 = "Hour stats on the count of response messages per client RPC";
        RPC_CLIENT_RESPONSE_COUNT_HOUR_VIEW = View.create(Name.create("grpc.io/client/response_count/hour"), str44, RpcMeasureConstants.RPC_CLIENT_RESPONSE_COUNT, MEAN, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_HOUR);
        String str45 = "Minute stats for server latency in msecs";
        RPC_SERVER_SERVER_LATENCY_MINUTE_VIEW = View.create(Name.create("grpc.io/server/server_latency/minute"), str45, RpcMeasureConstants.RPC_SERVER_SERVER_LATENCY, MEAN, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_MINUTE);
        String str46 = "Minute stats for request size in bytes";
        RPC_SERVER_REQUEST_BYTES_MINUTE_VIEW = View.create(Name.create("grpc.io/server/request_bytes/minute"), str46, RpcMeasureConstants.RPC_SERVER_REQUEST_BYTES, MEAN, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_MINUTE);
        String str47 = "Minute stats for response size in bytes";
        RPC_SERVER_RESPONSE_BYTES_MINUTE_VIEW = View.create(Name.create("grpc.io/server/response_bytes/minute"), str47, RpcMeasureConstants.RPC_SERVER_RESPONSE_BYTES, MEAN, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_MINUTE);
        String str48 = "Minute stats for rpc errors";
        RPC_SERVER_ERROR_COUNT_MINUTE_VIEW = View.create(Name.create("grpc.io/server/error_count/minute"), str48, RpcMeasureConstants.RPC_SERVER_ERROR_COUNT, MEAN, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_MINUTE);
        String str49 = "Minute stats for uncompressed request size in bytes";
        RPC_SERVER_UNCOMPRESSED_REQUEST_BYTES_MINUTE_VIEW = View.create(Name.create("grpc.io/server/uncompressed_request_bytes/minute"), str49, RpcMeasureConstants.RPC_SERVER_UNCOMPRESSED_REQUEST_BYTES, MEAN, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_MINUTE);
        String str50 = "Minute stats for uncompressed response size in bytes";
        RPC_SERVER_UNCOMPRESSED_RESPONSE_BYTES_MINUTE_VIEW = View.create(Name.create("grpc.io/server/uncompressed_response_bytes/minute"), str50, RpcMeasureConstants.RPC_SERVER_UNCOMPRESSED_RESPONSE_BYTES, MEAN, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_MINUTE);
        String str51 = "Minute stats for server elapsed time in msecs";
        RPC_SERVER_SERVER_ELAPSED_TIME_MINUTE_VIEW = View.create(Name.create("grpc.io/server/server_elapsed_time/minute"), str51, RpcMeasureConstants.RPC_SERVER_SERVER_ELAPSED_TIME, MEAN, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_MINUTE);
        String str52 = "Minute stats on the number of server RPCs started";
        RPC_SERVER_STARTED_COUNT_MINUTE_VIEW = View.create(Name.create("grpc.io/server/started_count/minute"), str52, RpcMeasureConstants.RPC_SERVER_STARTED_COUNT, COUNT, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_MINUTE);
        String str53 = "Minute stats on the number of server RPCs finished";
        RPC_SERVER_FINISHED_COUNT_MINUTE_VIEW = View.create(Name.create("grpc.io/server/finished_count/minute"), str53, RpcMeasureConstants.RPC_SERVER_FINISHED_COUNT, COUNT, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_MINUTE);
        String str54 = "Minute stats on the count of request messages per server RPC";
        RPC_SERVER_REQUEST_COUNT_MINUTE_VIEW = View.create(Name.create("grpc.io/server/request_count/minute"), str54, RpcMeasureConstants.RPC_SERVER_REQUEST_COUNT, MEAN, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_MINUTE);
        String str55 = "Minute stats on the count of response messages per server RPC";
        RPC_SERVER_RESPONSE_COUNT_MINUTE_VIEW = View.create(Name.create("grpc.io/server/response_count/minute"), str55, RpcMeasureConstants.RPC_SERVER_RESPONSE_COUNT, MEAN, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_MINUTE);
        String str56 = "Hour stats for server latency in msecs";
        RPC_SERVER_SERVER_LATENCY_HOUR_VIEW = View.create(Name.create("grpc.io/server/server_latency/hour"), str56, RpcMeasureConstants.RPC_SERVER_SERVER_LATENCY, MEAN, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_HOUR);
        String str57 = "Hour stats for request size in bytes";
        RPC_SERVER_REQUEST_BYTES_HOUR_VIEW = View.create(Name.create("grpc.io/server/request_bytes/hour"), str57, RpcMeasureConstants.RPC_SERVER_REQUEST_BYTES, MEAN, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_HOUR);
        String str58 = "Hour stats for response size in bytes";
        RPC_SERVER_RESPONSE_BYTES_HOUR_VIEW = View.create(Name.create("grpc.io/server/response_bytes/hour"), str58, RpcMeasureConstants.RPC_SERVER_RESPONSE_BYTES, MEAN, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_HOUR);
        String str59 = "Hour stats for rpc errors";
        RPC_SERVER_ERROR_COUNT_HOUR_VIEW = View.create(Name.create("grpc.io/server/error_count/hour"), str59, RpcMeasureConstants.RPC_SERVER_ERROR_COUNT, MEAN, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_HOUR);
        String str60 = "Hour stats for uncompressed request size in bytes";
        RPC_SERVER_UNCOMPRESSED_REQUEST_BYTES_HOUR_VIEW = View.create(Name.create("grpc.io/server/uncompressed_request_bytes/hour"), str60, RpcMeasureConstants.RPC_SERVER_UNCOMPRESSED_REQUEST_BYTES, MEAN, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_HOUR);
        String str61 = "Hour stats for uncompressed response size in bytes";
        RPC_SERVER_UNCOMPRESSED_RESPONSE_BYTES_HOUR_VIEW = View.create(Name.create("grpc.io/server/uncompressed_response_bytes/hour"), str61, RpcMeasureConstants.RPC_SERVER_UNCOMPRESSED_RESPONSE_BYTES, MEAN, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_HOUR);
        String str62 = "Hour stats for server elapsed time in msecs";
        RPC_SERVER_SERVER_ELAPSED_TIME_HOUR_VIEW = View.create(Name.create("grpc.io/server/server_elapsed_time/hour"), str62, RpcMeasureConstants.RPC_SERVER_SERVER_ELAPSED_TIME, MEAN, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_HOUR);
        String str63 = "Hour stats on the number of server RPCs started";
        RPC_SERVER_STARTED_COUNT_HOUR_VIEW = View.create(Name.create("grpc.io/server/started_count/hour"), str63, RpcMeasureConstants.RPC_SERVER_STARTED_COUNT, COUNT, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_HOUR);
        String str64 = "Hour stats on the number of server RPCs finished";
        RPC_SERVER_FINISHED_COUNT_HOUR_VIEW = View.create(Name.create("grpc.io/server/finished_count/hour"), str64, RpcMeasureConstants.RPC_SERVER_FINISHED_COUNT, COUNT, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_HOUR);
        String str65 = "Hour stats on the count of request messages per server RPC";
        RPC_SERVER_REQUEST_COUNT_HOUR_VIEW = View.create(Name.create("grpc.io/server/request_count/hour"), str65, RpcMeasureConstants.RPC_SERVER_REQUEST_COUNT, MEAN, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_HOUR);
        String str66 = "Hour stats on the count of response messages per server RPC";
        RPC_SERVER_RESPONSE_COUNT_HOUR_VIEW = View.create(Name.create("grpc.io/server/response_count/hour"), str66, RpcMeasureConstants.RPC_SERVER_RESPONSE_COUNT, MEAN, Arrays.asList(new TagKey[]{RpcMeasureConstants.RPC_METHOD}), INTERVAL_HOUR);
    }

    RpcViewConstants() {
        throw new AssertionError();
    }
}
