package com.mobiroller.constants;

import com.google.android.gms.ads.AdView;
import com.google.android.gms.analytics.Tracker;
import com.google.firebase.analytics.FirebaseAnalytics.Param;
import p043io.fabric.sdk.android.services.settings.SettingsJsonConstants;

public class Constants {
    public static String Applyze_BaseURL = "https://mobiroller.api.applyze.com/";
    public static String Applyze_ECommerce_BaseURL = null;
    public static String Applyze_Payment_Complete = "http://applyze-ecommerce-service/v1/paymentSuccess";
    public static String Applyze_Payment_Complete_1 = "https://dev.ecommerce.applyze.com/v2.0/paymentSuccess";
    public static String Applyze_Payment_Complete_2 = "/paymentSuccess";
    public static String Applyze_Payment_Failed = "http://applyze-ecommerce-service/v1/paymentFailure";
    public static String Applyze_Payment_Failed_1 = "https://dev.ecommerce.applyze.com/v2.0/paymentFailure";
    public static String Applyze_Payment_Failed_2 = "/paymentFailure";
    public static String Applyze_User_BaseURL = null;
    public static final String CALLBACK_URL = "www.mobiroller.com";
    public static final String CONSUMER_KEY = "Lnjil7tquAzUefgq7U1xg";
    public static final String CONSUMER_SECRET = "J2RnqX9rodvVd6XjgvxXggTcVJOI5Xgp7z7soBWPQ";
    public static final String DISPLAY_LANGUAGE = "Display_Language";
    public static final String DISPLAY_MESSAGE_ACTION = "com.mobiroller.preview.DISPLAY_MESSAGE";
    public static final String EXTRA_MESSAGE = "message";
    public static String E_COMMERCE_SCREEN_ID = "";
    public static final String INTENT_EXTRA_INTRO_MESSAGE = "introMsg";
    public static final String INTENT_EXTRA_IS_BACK_AVAILABLE = "isBackAvailable";
    public static final String INTENT_EXTRA_LOCAL_NAVIGATION_MODEL = "localObj";
    public static final String INTENT_EXTRA_MAIN_MODEL = "liveObj";
    public static final String INTENT_EXTRA_NAVIGATION_MODEL = "navObj";
    public static final String INTENT_EXTRA_PUSH_NOTIFIED = "pushNotified";
    public static final String KEY_CATALOG_CATEGORY = "catalogCategory";
    public static final String KEY_CATALOG_CATEGORY_PRODUCT = "catalogCategoryProduct";
    public static final String KEY_FROM_NO_NETWORK = "fromNoNetwork";
    public static final String KEY_IS_FROM_ACTIVITY = "isFromActivity";
    public static final String KEY_IS_FROM_CLASSIC_MENU = "isFromClassicMenu";
    public static final String KEY_LOCAL_NAVIGATION_MODEL = "localObj";
    public static final String KEY_PUSH_NOTIFIED = "pushNotified";
    public static final String KEY_RSS_LAYOUT_TYPE = "layoutType";
    public static final String KEY_RSS_POSITION = "position";
    public static final String KEY_RSS_TITLE = "rssTitle";
    public static final String KEY_SCREEN_ID = "screenId";
    public static final String KEY_SCREEN_ROLES = "roles";
    public static final String KEY_SCREEN_RSS_PUSH_TITLE = "rssPushTitle";
    public static final String KEY_SCREEN_TYPE = "screenType";
    public static final String KEY_SHOW_INTRO = "showIntro";
    public static final String KEY_SUB_SCREEN_TYPE = "screenSubType";
    public static final String KEY_UPDATE_DATE = "updateDate";
    public static String MobiRoller_BaseURL = "https://myapi.mobiroller.com/";
    public static String MobiRoller_FacebookName = "MobiRoller";
    public static String MobiRoller_FacebookURL = "https://www.facebook.com/MobiRoller";
    public static String MobiRoller_GooglePlusID = "114823517015940083565";
    public static String MobiRoller_GoogleURL = "https://plus.google.com/+Mobiroller";
    public static String MobiRoller_InstagramName = null;
    public static String MobiRoller_InstagramURL = "https://www.instagram.com/mobiroller";
    public static String MobiRoller_LinkedinURL = "https://www.linkedin.com/company/mobiroller";
    public static String MobiRoller_Location_Permission_First_Time = "MobiRoller_Location_Permission_First_Time";
    public static String MobiRoller_Preferences_ActionBarColor = "MobiRoller_Preferences_ActionBarColor";
    public static String MobiRoller_Preferences_AdUnitID = "MobiRoller_Preferences_AdUnitID";
    public static Tracker MobiRoller_Preferences_AnalyticsTracker = null;
    public static String MobiRoller_Preferences_AndroidVersion = "MobiRoller_Preferences_AndroidVersion";
    public static String MobiRoller_Preferences_AppCode = "MobiRoller_Preferences_AppCode";
    public static String MobiRoller_Preferences_App_Version = "MobiRoller_Preferences_App_Version";
    public static String MobiRoller_Preferences_AskBeforeExit = "MobiRoller_Preferences_AskBeforeExit";
    public static String MobiRoller_Preferences_Assets_Directory_Path = "Files/";
    public static String MobiRoller_Preferences_AutoInterstitialStatus = "MobiRoller_Preferences_AutoInterstitialStatus";
    public static String MobiRoller_Preferences_BannerAdUnitID = "MobiRoller_Preferences_BannerAdUnitID";
    public static AdView MobiRoller_Preferences_BannerAdView = null;
    public static String MobiRoller_Preferences_BleshServiceStatus = "MobiRoller_Preferences_BleshServiceStatus";
    public static String MobiRoller_Preferences_CharSet = "UTF-8";
    public static String MobiRoller_Preferences_Chat_Minimum_Version = "MobiRoller_Preferences_Chat_Minimum_Version";
    public static String MobiRoller_Preferences_Chat_Minimum_Version_Setted = "MobiRoller_Preferences_Chat_Minimum_Version_Setted";
    public static String MobiRoller_Preferences_CurrentLang = "MobiRoller_Preferences_CurrentLang";
    public static String MobiRoller_Preferences_DefaultLang = "MobiRoller_Preferences_DefaultLang";
    public static String MobiRoller_Preferences_DeviceModel = "MobiRoller_Preferences_DeviceModel";
    public static String MobiRoller_Preferences_Device_ID = "Mobiroller_Preferences_Device_ID";
    public static String MobiRoller_Preferences_Expiration_Time = "MobiRoller_Preferences_Expiration_Time";
    public static String MobiRoller_Preferences_FCM_Token = "MobiRoller_Preferences_FCM_Token";
    public static String MobiRoller_Preferences_FirebaseToken = "MobiRoller_Preferences_FirebaseToken";
    public static String MobiRoller_Preferences_First_Time_Language = "MobiRoller_Preferences_First_Time_Language";
    public static String MobiRoller_Preferences_Google_Sign_Account = "MobiRoller_Preferences_Google_Sign_Account";
    public static String MobiRoller_Preferences_IN_APP_PURCHASE_URL = "aveInAppPurchase_";
    public static String MobiRoller_Preferences_InAppPurchaseActive = "MobiRoller_Preferences_InAppPurchaseActive";
    public static String MobiRoller_Preferences_InterstitialClickInterval = "MobiRoller_Preferences_InterstitialClickInterval";
    public static String MobiRoller_Preferences_InterstitialMultipleDisplayEnabled = "MobiRoller_Preferences_InterstitialMultipleDisplayEnabled";
    public static String MobiRoller_Preferences_InterstitialTimeInterval = "MobiRoller_Preferences_InterstitialTimeInterval";
    public static String MobiRoller_Preferences_Interstitial_Click = "MobiRoller_Preferences_Interstitial_Click";
    public static String MobiRoller_Preferences_Interstitial_Click_Count = "MobiRoller_Preferences_Interstitial_Click_Count";
    public static String MobiRoller_Preferences_Interstitial_Timer = "MobiRoller_Preferences_Interstitial_Timer";
    public static String MobiRoller_Preferences_IntroMessage = "MobiRoller_Preferences_IntroMessage";
    public static String MobiRoller_Preferences_IsAdEnabled = "MobiRoller_Preferences_IsAdEnabled";
    public static String MobiRoller_Preferences_IsBannerAdEnabled = "MobiRoller_Preferences_IsBannerAdEnabled";
    public static String MobiRoller_Preferences_IsChatAvailable = "MobiRoller_Preferences_IsChatAvailable";
    public static String MobiRoller_Preferences_IsChatValidated = "MobiRoller_Preferences_IsChatValidated";
    public static String MobiRoller_Preferences_IsGoogleSignInActive = "MobiRoller_Preferences_IsGoogleSignInActive";
    public static String MobiRoller_Preferences_IsNativeAdEnabled = "MobiRoller_Preferences_IsNativeAdEnabled";
    public static String MobiRoller_Preferences_IsUserAgremeentActive = "MobiRoller_Preferences_IsUserAgremeentActive";
    public static String MobiRoller_Preferences_IsYoutubeChannelSubscribed = "MobiRoller_Preferences_IsYoutubeChannelSubscribed";
    public static String MobiRoller_Preferences_Is_Favorite_Active = "MobiRoller_Preferences_Is_Favorite_Active";
    public static String MobiRoller_Preferences_LanguageSetByUser = "MobiRoller_Preferences_LanguageSetByUser";
    public static String MobiRoller_Preferences_LocaleCodes = "MobiRoller_Preferences_LocaleCodes";
    public static String MobiRoller_Preferences_Location_Never_Ask = "MobiRoller_Preferences_Location_Never_Ask";
    public static String MobiRoller_Preferences_Location_Permission_Count = "MobiRoller_Preferences_Location_Permission_Count";
    public static String MobiRoller_Preferences_Location_Permission_Given = "MobiRoller_Preferences_Location_Permission_Given";
    public static String MobiRoller_Preferences_LoginBackgroundURL = "MobiRoller_Preferences_LoginBackgroundURL";
    public static String MobiRoller_Preferences_LoginRegisterLayoutChoose = "MobiRoller_Preferences_LoginRegisterLayoutChoose";
    public static String MobiRoller_Preferences_LogoURL = "MobiRoller_Preferences_LogoURL";
    public static String MobiRoller_Preferences_MobiRollerBadgeX = "MobiRoller_Preferences_MobiRollerBadgeX";
    public static String MobiRoller_Preferences_MobiRollerBadgeY = "MobiRoller_Preferences_MobiRollerBadgeY";
    public static String MobiRoller_Preferences_MobiRoller_Badge_Check_Response = "MobiRoller_Preferences_MobiRoller_Badge_Check_Response";
    public static String MobiRoller_Preferences_MobiRoller_Badge_Count = "MobiRoller_Preferences_MobiRoller_Badge_Count";
    public static String MobiRoller_Preferences_MobiRoller_Badge_First_Open = "MobiRoller_Preferences_MobiRoller_Badge_First_Open";
    public static String MobiRoller_Preferences_MobiRoller_Badge_Total_Count = "MobiRoller_Preferences_MobiRoller_Badge_Total_Count";
    public static String MobiRoller_Preferences_MobiRoller_Badge_Url = "MobiRoller_Preferences_MobiRoller_Badge_Url";
    public static String MobiRoller_Preferences_MotionHeight = "MobiRoller_Preferences_MotionHeight";
    public static String MobiRoller_Preferences_MotionWidth = "MobiRoller_Preferences_MotionWidth";
    public static String MobiRoller_Preferences_NAVUrl = "aveNavigation_";
    public static String MobiRoller_Preferences_NativeAdUnitID = "MobiRoller_Preferences_NativeAdUnitID";
    public static String MobiRoller_Preferences_Notification = "MobiRoller_Preferences_Notification";
    public static String MobiRoller_Preferences_NotificationCount = "MobiRoller_Preferences_NotificationCount";
    public static String MobiRoller_Preferences_NotificationSound = "MobiRoller_Preferences_NotificationSound";
    public static String MobiRoller_Preferences_PaddingHeight = "MobiRoller_Preferences_PaddingHeight";
    public static String MobiRoller_Preferences_Password = "MobiRoller_Preferences_Password";
    public static String MobiRoller_Preferences_PasswordId = "MobiRoller_Preferences_PasswordId";
    public static String MobiRoller_Preferences_PollfishApiKey = "MobiRoller_Preferences_PollfishApiKey";
    public static String MobiRoller_Preferences_PollfishStatus = "MobiRoller_Preferences_PollfishStatus";
    public static String MobiRoller_Preferences_ProgressAnimationColor = "MobiRoller_Preferences_ProgressAnimationColor";
    public static String MobiRoller_Preferences_ProgressAnimationType = "MobiRoller_Preferences_ProgressAnimationType";
    public static String MobiRoller_Preferences_RateApp = "MobiRoller_Preferences_RateApp";
    public static String MobiRoller_Preferences_RefreshIntro = "MobiRoller_Preferences_RefreshIntro";
    public static String MobiRoller_Preferences_Registration_ID = "MobiRoller_Preferences_Registration_ID";
    public static String MobiRoller_Preferences_RememberMe = "MobiRoller_Preferences_RememberMe";
    public static String MobiRoller_Preferences_ReturnAdsStatus = "MobiRoller_Preferences_ReturnAdsStatus";
    public static String MobiRoller_Preferences_SelectLangOnStart = "MobiRoller_Preferences_SelectLangOnStart";
    public static String MobiRoller_Preferences_Show_MobiRoller_Badge = "MobiRoller_Preferences_Show_MobiRoller_Badge";
    public static String MobiRoller_Preferences_SplashAdsStatus = "MobiRoller_Preferences_SplashAdsStatus";
    public static int MobiRoller_Preferences_StandardHeight = 568;
    public static int MobiRoller_Preferences_StandardWidth = 320;
    public static String MobiRoller_Preferences_StappAdsAutoInterstitialType = "MobiRoller_Preferences_StappAdsAutoInterstitialType";
    public static String MobiRoller_Preferences_StappAdsAutoInterstitialValue = "MobiRoller_Preferences_StappAdsAutoInterstitialValue";
    public static String MobiRoller_Preferences_Storage_Never_Ask = "MobiRoller_Preferences_Storage_Never_Ask";
    public static String MobiRoller_Preferences_TabHeight = "MobiRoller_Preferences_TabHeight";
    public static String MobiRoller_Preferences_ThirdPartyAdsStatus = "MobiRoller_Preferences_ThirdPartyAdsStatus";
    public static String MobiRoller_Preferences_TitleColor = "Mobiroller_Preferences_TitleColor";
    public static String MobiRoller_Preferences_TitleSelectedColor = "Mobiroller_Preferences_TitleSelectedColor";
    public static String MobiRoller_Preferences_UserAgremeent = "MobiRoller_Preferences_UserAgremeent";
    public static String MobiRoller_Preferences_UserEmail = "MobiRoller_Preferences_UserEmail";
    public static String MobiRoller_Preferences_UserId = "MobiRoller_Preferences_UserId";
    public static String MobiRoller_Preferences_UserIsAvailableForChat = "MobiRoller_Preferences_UserIsAvailableForChat";
    public static String MobiRoller_Preferences_UserIsChatAdmin = "MobiRoller_Preferences_UserIsChatAdmin";
    public static String MobiRoller_Preferences_UserIsChatMod = "MobiRoller_Preferences_UserIsChatMod";
    public static String MobiRoller_Preferences_UserIsSuperUser = "MobiRoller_Preferences_UserIsSuperUser";
    public static String MobiRoller_Preferences_UserLoginNameSurname = "MobiRoller_Preferences_UserLoginNameSurname";
    public static String MobiRoller_Preferences_UserLoginStatus = "MobiRoller_Preferences_UserLoginStatus";
    public static String MobiRoller_Preferences_UserLogin_IsLoginActive = "MobiRoller_Preferences_UserLogin_IsLoginActive";
    public static String MobiRoller_Preferences_UserLogin_IsRegisterationActive = "MobiRoller_Preferences_UserLogin_IsRegisterationActive";
    public static String MobiRoller_Preferences_UserName = "MobiRoller_Preferences_UserName";
    public static String MobiRoller_Preferences_UserPassword = "MobiRoller_Preferences_UserPassword";
    public static String MobiRoller_Preferences_UserRole = "MobiRoller_Preferences_UserRole";
    public static String MobiRoller_Preferences_UserSessionToken = "MobiRoller_Preferences_UserSessionToken";
    public static String MobiRoller_Preferences_User_Login_Model = "MobiRoller_Preferences_User_Login_Model";
    public static String MobiRoller_Preferences_ValueSetIndex = "MobiRoller_Preferences_ValueSetIndex";
    public static String MobiRoller_Preferences_VideoAdsStatus = "MobiRoller_Preferences_VideoAdsStatus";
    public static String MobiRoller_Preferences_Youtube_Channel_Detail = "MobiRoller_Preferences_Youtube_Channel_Detail";
    public static String MobiRoller_Preview_Notification_Model = "previewNotification";
    public static String MobiRoller_Preview_UserName = "preview";
    public static String MobiRoller_SignUpURL = "https://my.mobiroller.com/Register";
    public static String MobiRoller_TwitterName = null;
    public static String MobiRoller_TwitterURL = "https://www.twitter.com/mobiroller";
    public static String MobiRoller_YoutubeURL = "https://m.youtube.com/user/mobiroller";
    public static String Mobiroller_Preferences_FilePath = null;
    public static String Mobiroller_Preferences_PackageName_Activities = "com.mobiroller.activities";
    public static String Mobiroller_Preferences_TabMenu = "Mobiroller_Preferences_TabMenu";
    public static final String NEW_LINE = "\n";
    public static String NOTIFICATION_CONTENT = null;
    public static String NOTIFICATION_EXTERNAL = "external";
    public static String NOTIFICATION_INTERNAL = "internal";
    public static String NOTIFICATION_TYPE_APP = null;
    public static String NOTIFICATION_TYPE_CONTENT = null;
    public static String NOTIFICATION_TYPE_WEB = "web";
    public static String NOTIFICATION_TYPE_WEB_CONTENT = null;
    public static final String PREVIEW_LOGIN_LOG_URL;
    public static final long REGISTRATION_EXPIRY_TIME_MS = 604800000;
    public static final String SERVER_SESSION_START_URL;
    public static final int TIMEOUT_MILLI_SECONDS = 3000;
    public static final String USER_SECRET = "user_secret";
    public static final String USER_TOKEN = "user_token";
    public static String firstTime = "firstTime";
    public static String isTabActive = "isTabActive";

    static {
        StringBuilder sb = new StringBuilder();
        sb.append(Applyze_BaseURL);
        sb.append("ecommerce/");
        Applyze_ECommerce_BaseURL = sb.toString();
        StringBuilder sb2 = new StringBuilder();
        sb2.append(Applyze_BaseURL);
        sb2.append("appuser/v1/");
        Applyze_User_BaseURL = sb2.toString();
        String str = "mobiroller";
        MobiRoller_TwitterName = str;
        MobiRoller_InstagramName = str;
        StringBuilder sb3 = new StringBuilder();
        sb3.append(MobiRoller_BaseURL);
        sb3.append("MobiRoller/LogStageLogin");
        PREVIEW_LOGIN_LOG_URL = sb3.toString();
        StringBuilder sb4 = new StringBuilder();
        sb4.append(MobiRoller_BaseURL);
        sb4.append("AveAnalytics/SessionStart");
        SERVER_SESSION_START_URL = sb4.toString();
        String str2 = Param.CONTENT;
        NOTIFICATION_CONTENT = str2;
        NOTIFICATION_TYPE_CONTENT = str2;
        String str3 = SettingsJsonConstants.APP_KEY;
        NOTIFICATION_TYPE_APP = str3;
        NOTIFICATION_TYPE_WEB_CONTENT = str3;
    }
}
